import { Tabs } from '@heroui/react';
import { useContext, useState } from 'react';
import { ArrowUpRight, Cloud, Copy, Database, KeyRound, LockKeyhole, Server, Terminal } from 'lucide-react';
import { copy, ToastContext, useApi } from '../lib';
import type { Config } from '../types';
import { Badge, Button, ErrorBox, Loading, PageTitle } from '../components';

export function Settings() {
  const { data, error, loading } = useApi<Config>('/config'), notify = useContext(ToastContext), [language, setLanguage] = useState('curl'), [tab, setTab] = useState('connection');
  const endpoint = `${location.origin}/v1`;
  const examples: Record<string, string> = {
    curl: `curl ${endpoint}/chat/completions \\\n  -H "Authorization: Bearer $EDGEGATE_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "model": "gpt-4.1",\n    "messages": [{"role": "user", "content": "你好"}],\n    "stream": false\n  }'`,
    Anthropic: `curl ${location.origin}/v1/messages \\\n  -H "x-api-key: $EDGEGATE_API_KEY" \\\n  -H "anthropic-version: 2023-06-01" \\\n  -H "Content-Type: application/json" \\\n  -d '{"model":"claude-sonnet-4-5","max_tokens":1024,"messages":[{"role":"user","content":"你好"}],"stream":true}'`,
    Python: `from openai import OpenAI\nimport os\n\nclient = OpenAI(\n    base_url="${endpoint}",\n    api_key=os.environ["EDGEGATE_API_KEY"],\n)\nresponse = client.chat.completions.create(\n    model="gpt-4.1",\n    messages=[{"role": "user", "content": "你好"}],\n)\nprint(response.choices[0].message.content)`,
  };
  return <><PageTitle eyebrow="07 / CONFIGURATION" title="网关设置" description="管理连接信息，检查凭据状态，获取应用接入代码。" /><ErrorBox message={error} />{loading && !data ? <Loading /> : data && <div className="settings-layout">
    <section className="surface settings-main"><Tabs selectedKey={tab} onSelectionChange={key => setTab(String(key))} className="workspace-tabs"><Tabs.ListContainer><Tabs.List aria-label="设置分类"><Tabs.Tab id="connection"><Server size={16} />连接信息<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="credentials"><LockKeyhole size={16} />环境凭据<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="examples"><Terminal size={16} />接入代码<Tabs.Indicator /></Tabs.Tab></Tabs.List></Tabs.ListContainer>
      <Tabs.Panel id="connection"><div className="settings-section"><h2>基础设施与连接</h2><p>当前 Worker 使用的 Cloudflare 资源。基础变量通过部署配置管理。</p><div className="settings-rows"><div><span><Cloud size={17} />Account ID</span><code>{data.account_id || '尚未配置'}</code></div><div><span><Cloud size={17} />AI Gateway ID</span><code>{data.gateway_id}</code></div><div><span><LockKeyhole size={17} />供应商密钥</span><strong>D1 · AES-256-GCM 加密</strong></div><div><span><Database size={17} />业务数据库</span><strong>D1 · DB</strong></div><div><span><KeyRound size={17} />管理会话</span><strong>Workers KV · KV</strong></div><div><span><Terminal size={17} />日志与分析</span><strong>Cloudflare AI Gateway</strong></div></div><div className="settings-note">Account ID、Gateway ID 等变量在 <code>wrangler.jsonc</code> 中配置。日志采集、正文保留、缓存与费用设置由 Cloudflare AI Gateway 管理。</div></div></Tabs.Panel>
      <Tabs.Panel id="credentials"><div className="settings-section"><h2>环境凭据</h2><p>仅显示配置状态。通过 <code>wrangler secret put</code> 或 Cloudflare 控制台管理 Secret。</p><div className="settings-rows">{[{ label: 'CF_API_TOKEN', ready: data.control_token_configured }, { label: 'CF_AI_TOKEN', ready: data.ai_token_configured }, { label: 'CF_AIG_TOKEN', ready: data.aig_token_configured }, { label: 'ENCRYPTION_KEY', ready: data.encryption_configured }].map(item => <div key={item.label}><code>{item.label}</code><Badge tone={item.ready ? 'green' : 'amber'}>{item.ready ? '已配置' : '未配置'}</Badge></div>)}</div><div className="settings-note">CF_API_TOKEN 需要 AI Gateway 读写、Account Analytics 读取权限。供应商密钥使用 ENCRYPTION_KEY 加密保存在 D1，无需 Secrets Store。推理 Token 需要 AI Gateway Run 权限，可配置独立 CF_AIG_TOKEN；留空则使用 CF_API_TOKEN。</div></div></Tabs.Panel>
      <Tabs.Panel id="examples"><div className="settings-section"><h2>连接你的应用</h2><p>选择客户端，将 Base URL 和应用 API Key 配置到你的服务端。</p><div className="api-endpoint-row"><span>API Base URL</span><code>{endpoint}</code><Button variant="secondary" aria-label="复制 API 地址" onClick={() => copy(endpoint, notify)}><Copy size={15} /></Button></div><div className="example-tabs"><div>{Object.keys(examples).map(name => <button type="button" key={name} aria-pressed={name === language} className={name === language ? 'selected' : ''} onClick={() => setLanguage(name)}>{name}</button>)}</div><Button variant="ghost" onClick={() => copy(examples[language], notify)}><Copy size={15} />复制代码</Button></div><pre className="api-code">{examples[language]}</pre></div></Tabs.Panel>
    </Tabs></section>
    <aside className="settings-aside"><section className="surface settings-guide"><Cloud size={29} /><div className="inline-heading"><h3>AI Gateway</h3><Badge tone={data.account_id && data.control_token_configured ? 'green' : 'amber'}>{data.account_id && data.control_token_configured ? '已配置' : '待连接'}</Badge></div><p>在 Cloudflare 管理自定义服务商、日志保留与缓存策略。供应商密钥可在本程序中加密保存。</p><a className="text-link" href={data.dashboard_url} target="_blank" rel="noreferrer">打开 Cloudflare<ArrowUpRight size={15} /></a></section><section className="surface settings-guide"><Terminal size={25} /><h3>统一 API 端点</h3><p>客户端协议自动转换，模型范围按应用密钥的标签和白名单确定。</p>{[{ name: 'OpenAI Chat Completions', path: 'POST /v1/chat/completions' }, { name: 'Anthropic Messages', path: 'POST /v1/messages' }, { name: '可用模型', path: 'GET /v1/models' }].map(protocol => <div className="protocol-item" key={protocol.path}><span>{protocol.name}</span><code>{protocol.path}</code></div>)}</section><a href="https://developers.cloudflare.com/ai-gateway/usage/rest-api/" className="text-link" target="_blank" rel="noreferrer">Cloudflare 文档<ArrowUpRight size={16} /></a></aside>
    </div>}</>;
}
